POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Testing REST Client in VS Code",
  "important": true
}

###

GET http://localhost:3001/api/notes

###
DELETE http:localhost:3001/api/notes:
