POST http://localhost:3001/api/notes
x-password: Jeanne
Content-Type: application/json

{
    "content": " Tuone na Headers, Midleware logger tested successfuly",
    "import": "false"
}

### 
# Test Updating an existing note

PUT https://your-app-name.onrender.com/api/notes/
x-password: Jeanne
Content-Type: application/json

{
  "content": "HTML is easy",
  "important": true
}

###

GET http://localhost:3001/api/notes
x-password: Jeanne
Content-Type: application/json
### 

DELETE http://localhost:3001/api/notes/6

### 



